// <auto-generated />
using CheckerApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CheckerApi.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20180520100523_AddedLocation")]
    partial class AddedLocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CheckerApi.DTO.DataDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AcceptedSpeed");

                    b.Property<string>("Algo");

                    b.Property<bool>("Alive");

                    b.Property<double>("LimitSpeed");

                    b.Property<int>("NiceHashDataCenter");

                    b.Property<string>("NiceHashId");

                    b.Property<double>("Price");

                    b.Property<DateTime>("RecordDate");

                    b.Property<string>("Type");

                    b.Property<string>("Workers");

                    b.HasKey("ID");

                    b.ToTable("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
